import type { Metadata } from 'next';
import { ThemeProvider } from '@mui/material';
import { MyTheme } from './MyTheme';
import { Inter } from 'next/font/google';
import { Header, Modal } from '@/components';
import { cookies } from 'next/headers';
import { ModalProvider } from './context';
import '../styles/globals.css';

export const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-inter'
});

export const metadata: Metadata = {
  title: 'SPORT REC',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesList = cookies();
  const isAuthCookie = cookiesList.get('isAuth');

  return (
    <ThemeProvider theme={MyTheme}>
      <ModalProvider>
        <html lang='en'>
          <body
            className={inter.className}
            style={{
              background: '#F1F3F7',
              fontSize: '14px',
              fontFamily: `${inter.style.fontFamily} !important`
            }}
          >
            <Header isAuth={isAuthCookie?.value} />
            {children}
            <div id='portal'></div>
            <Modal />
          </body>
        </html>
      </ModalProvider>
    </ThemeProvider>
  );
}
